# Generated by Django 4.2.11 on 2026-02-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_parking_extras_and_reviews'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkingreview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='parkingreview',
            constraint=models.UniqueConstraint(fields=('parking', 'user'), name='uniq_review_per_user_per_parking'),
        ),
    ]
